version: '3.1'
services:
  web:
    # build: .
    image: alerta/alerta-web
    # volumes:
      # - $PWD/config/alertad.conf.example:/app/alertad.conf
      # - $PWD/config/alerta.conf.example:/app/alerta.conf
      # - $PWD/config/config.json.example:/web/config.json
    ports:
      - 9080:8080
    volumes:
      - $PWD/config/alertad.conf:/app/alertad.conf
    depends_on:
      - db0
    environment:
      # - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=mongodb://db0:27017/monitoring?replicaSet=rs0
      - MONGO_INITDB_DATABASE=monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - ADMIN_PASSWORD=super-secret # default is "alerta"
      - ADMIN_KEY=demo-key  # assigned to first user in ADMIN_USERS
      # - PLUGINS=remote_ip,reject,heartbeat,blackout,normalise,enhance
    restart: always

  db0:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./mongodb/0:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
    restart: always

  db1:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./mongodb/1:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all" ]
    restart: always

  db2:
    image: mongo
    ports:
      - 27017
    volumes:
      - ./mongodb/2:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all" ]
    restart: always

networks:
  net:
