apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alerta.fullname" . }}
  labels:
    app: {{ template "alerta.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.alertaAdminPassword }}
  alerta-admin-password:  {{ .Values.alertaAdminPassword | b64enc | quote }}
  {{ else }}
  alerta-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
