#!/bin/bash

VCS_REF=$(git rev-parse --short HEAD)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VERSION=$(cat VERSION)

docker-compose -f docker-compose.test.yml build \
  --build-arg VCS_REF=$VCS_REF \
  --build-arg BUILD_DATE=$BUILD_DATE \
  --build-arg VERSION=$VERSION

docker-compose -f docker-compose.test.yml up \
  --renew-anon-volumes \
  --exit-code-from tester
