name: Push to DockerHub

on:
  workflow_dispatch:
  branches:
    - "master"
    - "feature/*"
  push:
    tags:
      - "v*"

env:
  # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  REGISTRY: registry.hub.docker.com
  IMAGE_NAME: alerta/alerta-web

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker Lint
        id: docker-lint
        run: |
          docker run --rm -i ghcr.io/hadolint/hadolint hadolint \
          --ignore DL3008 \
          --ignore DL3059 \
          - < Dockerfile
      - name: Run tests
        id: smoketest
        run: >-
          BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          RELEASE=$(cat VERSION)
          VERSION=${{ github.sha }}
          docker compose
          -f tests/docker-compose.test.mongodb.yml
          up
          --build
          --quiet-pull
          --exit-code-from tester
      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: failure()

  push:
    name: Docker Push
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    env:
      REPOSITORY_URL: registry.hub.docker.com
      IMAGE_NAME: alerta/alerta-web

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REPOSITORY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          pull: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            RELEASE=$(cat VERSION)
            VERSION=${{ github.sha }}

      # - uses: act10ns/slack@v2
      #   with:
      #     status: ${{ job.status }}
      #     steps: ${{ toJson(steps) }}
      #   if: always()
